window.RACE_CONFIG = {
  version: "2026.08.16.43",
  title: "The Bitcoin Bottom Derby",
  subtitle: "Five public calls. Live race order stays fun day-to-day, while the official October 6 winner is the call closest to Bitcoin's contest low.",
  startDate: "2026-08-11T18:00:00Z",
  endDate: "2026-10-07T04:59:59Z",
  startPrice: 63559,
  dailyCloseHourUtc: 0,
  data: {
    productId: "BTC-USD",
    tickerUrl: "https://api.exchange.coinbase.com/products/BTC-USD/ticker",
    candlesUrl: "https://api.exchange.coinbase.com/products/BTC-USD/candles",
    fallbackTickerUrl: "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd",
    liveRefreshMs: 60000,
    historyRefreshMs: 15 * 60 * 1000
  },
  betting: {
    // Shared public voting is configured separately in supabase-config.js.
    voteStorageKey: "bitcoin-bottom-derby-vote",
    voteCountsStorageKey: "bitcoin-bottom-derby-local-book",
    voteLogStorageKey: "bitcoin-bottom-derby-vote-log",
    seedVotes: { whitesw0n: 7, tom: 22, tatiana: 27, rodster: 14, bike: 9 },
    note: "One locked pick per verified Discord member."
    , ownerLogKey: "RL_BottomDerby_2026"
  },
  racers: [
    {
      id: "whitesw0n",
      name: "WhiteSw0n",
      avatar: "assets/realistic-v43/whitesw0n/avatar.jpg",
      discordAvatar: "assets/avatar-whitesw0n.png",
      exhibition: false,
      motion: "gallop",
      color: "#7be3ff",
      darkColor: "#2a6d85",
      horseColor: "#e9ecef",
      horseDark: "#b8c0c8",
      silkText: "SW0N",
      target: 37999,
      displayPick: "$37,999",
      note: "fuzzy llama racer",
      liveRuleText: "Official finish uses the closest call to the contest low.",
      finalRuleText: "Can win the race if BTC reaches $37,999 or lower."
    },
    {
      id: "tom",
      name: "Tom",
      avatar: "assets/realistic-v43/tom/avatar.jpg",
      discordAvatar: "assets/avatar-tom.png",
      racerArt: "assets/racers/racer-tom.png",
      motion: "gallop",
      color: "#f5bd47",
      darkColor: "#805013",
      horseColor: "#4b382f",
      horseDark: "#1d1714",
      silkText: "TOM",
      target: 59000,
      displayPick: "Bottom is in",
      note: "max $59k if there's one more flush",
      liveRuleText: "Tied with Tatiana while BTC stays above $59,000.",
      finalRuleText: "Official finish uses the closest call to the contest low."
    },
    {
      id: "tatiana",
      name: "Tatiana",
      avatar: "assets/realistic-v43/tatiana/avatar.jpg",
      discordAvatar: "assets/avatar-tatiana.png",
      racerArt: "assets/racers/racer-tatiana.png",
      motion: "gallop",
      color: "#bdc9d8",
      darkColor: "#657487",
      horseColor: "#c56d5c",
      horseDark: "#793d35",
      silkText: "TATIANA",
      target: 53300,
      displayPick: "Bottom is in",
      note: "max $53.3k for bullish divergence low",
      liveRuleText: "Shares the live lead with Tom until $59k breaks.",
      finalRuleText: "Official finish uses the closest call to the contest low."
    },
    {
      id: "rodster",
      name: "Rodster",
      avatar: "assets/realistic-v43/rodster/avatar.jpg",
      discordAvatar: "assets/avatar-rodster.png",
      racerArt: "assets/racers/racer-rodster.png",
      motion: "gallop-aura",
      color: "#6dbbff",
      darkColor: "#255f8b",
      horseColor: "#5f5a66",
      horseDark: "#2c2732",
      silkText: "RODSTER",
      target: 47976,
      displayPick: "$47,976",
      note: "",
      liveRuleText: "Takes the live lead if BTC reaches $47,976 or lower.",
      finalRuleText: "Official finish uses the closest call to the contest low."
    },
    {
      id: "bike",
      name: "Bike",
      avatar: "assets/realistic-v43/bike/avatar.jpg",
      discordAvatar: "assets/avatar-bike.png",
      racerArt: "assets/racers/racer-bike.png",
      motion: "pedal",
      color: "#f7b64d",
      darkColor: "#8d5b16",
      horseColor: "#c8d3d7",
      horseDark: "#7c878f",
      silkText: "BIKE",
      target: 38750,
      displayPick: "$38,750",
      note: "",
      liveRuleText: "Steals the live lead if BTC reaches $38,750 or lower.",
      finalRuleText: "Official finish uses the closest call to the contest low."
    }
  ]
};
